[features]
hardware = []
[package]
name = "doser_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
doser_hardware = { path = "../doser_hardware" }
toml = "0.8"
doser_core = { path = "../doser_core" }
eyre = "0.6.12"
csv = "1.3.1"
