[pins]
hx711_dt = 5
hx711_sck = 6
motor_step = 17
motor_dir = 27

[filter]
ma_window = 5
median_window = 3
sample_rate_hz = 80

[control]
speed_bands = [
    { threshold_g = 1.0, sps = 1100 },
    { threshold_g = 0.5, sps = 450 },
    { threshold_g = 0.2, sps = 200 },
]
hysteresis_g = 0.07
epsilon_g = 0.08

[safety]
max_run_ms = 45000
max_overshoot_g = 0.6
no_progress_epsilon_g = 0.05
no_progress_ms = 1300

[timeouts]
sensor_ms = 50
settle_ms = 800
