[package]
name = "doser_hardware"
version = "0.1.0"
edition = "2024"

[dependencies]
doser_traits = { path = "../doser_traits" }
thiserror = "1"
rppal = { version = "0.17", optional = true }
tracing = "0.1"

[features]
hardware = ["rppal"]
