[package]
name = "doser_hardware"
version = "0.1.0"
edition = "2024"

[dependencies]
doser_traits = { path = "../doser_traits" }
thiserror = "1"
tracing = "0.1"

[features]
# Hardware feature flips on hardware-backed modules, but rppal is only pulled on ARM targets.
hardware = []

[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))'.dependencies]
rppal = "0.17"
