[package]
name = "doser_config"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = { workspace = true }
csv = "1"
eyre = "0.6"

[dev-dependencies]
tempfile = "3"
rstest = "0.23"
