name: CI

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build and test (simulation only)
        env:
          RUSTFLAGS: "-D warnings"
        run: |
          cargo build --workspace --no-default-features
          cargo test --workspace --no-default-features

  test-hardware-feature:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check hardware feature compiles
        run: |
          cargo build -p doser_hardware --features hardware --no-default-features
          cargo build -p doser_cli --features hardware --no-default-features
